sudo: required
language: python
services:
  - docker
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install -r test-requirements.txt
before_script:
  - ./bootstrap 127.0.0.1
script: ./run-tests.sh 127.0.0.1
after_success:
  - codecov
deploy:
  distributions: bdist_wheel sdist
  provider: pypi
  user: crad
  on:
    python: 2.7
    tags: true
    all_branches: true
  password:
    not-set
cache:
  directories:
    - $HOME/.pip-cache/
